In [3]:
import numpy as np

# 1. Creating 1D, 2D and 3D Arrays

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array:")
print(arr1)

print("\n2D Array:")
print(arr2)

print("\n3D Array:")
print(arr3)


# 2. Dimensions, Shape and Data Type

print("\nDimensions of arr1:", arr1.ndim)
print("Dimensions of arr2:", arr2.ndim)
print("Dimensions of arr3:", arr3.ndim)

print("Shape of arr2:", arr2.shape)
print("Data type of arr1:", arr1.dtype)


# 3. Indexing

print("\nIndexing:")
print("First element:", arr1[0])
print("Third element:", arr1[2])
print("Last element:", arr1[-1])

print("2D element:", arr2[1, 2])


# 4. Slicing

print("\nSlicing:")
print("1D slice:", arr1[1:4])
print("2D slice:")
print(arr2[:, 1:])


# 5. Reshaping

arr = np.arange(1, 13)

print("\nOriginal Array:")
print(arr)

reshaped = arr.reshape(3, 4)

print("Reshaped Array:")
print(reshaped)


# 6. Creating Arrays

print("\nZeros:")
print(np.zeros((2, 3)))

print("\nOnes:")
print(np.ones((2, 3)))

print("\nArange:")
print(np.arange(1, 11))

print("\nLinspace:")
print(np.linspace(0, 1, 5))


# 7. Mathematical Operations

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("\nMathematical Operations:")
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


# 8. Vectorized Operations

numbers = np.array([1, 2, 3, 4, 5])

print("\nVectorized Operations:")
print("Square:", numbers ** 2)
print("Multiply by 2:", numbers * 2)
print("Add 10:", numbers + 10)


# 9. Boolean Masking

marks = np.array([45, 67, 89, 32, 76, 91])

print("\nBoolean Masking:")
print("Marks greater than or equal to 50:")
print(marks[marks >= 50])


# 10. Broadcasting

numbers = np.array([10, 20, 30, 40])

print("\nBroadcasting:")
print("Add 5:", numbers + 5)
print("Multiply by 2:", numbers * 2)

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix + 10:")
print(matrix + 10)


# 11. Aggregate Functions

data = np.array([10, 20, 30, 40, 50])

print("\nAggregate Functions:")
print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))


# 12. Aggregate Functions on 2D Array

data2 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("\n2D Aggregate Functions:")
print("Sum:", np.sum(data2))
print("Mean:", np.mean(data2))
print("Minimum:", np.min(data2))
print("Maximum:", np.max(data2))
print("Median:", np.median(data2))


# 13. Aggregate Functions Using Axis

print("\nAxis Operations:")
print("Column-wise Sum:", np.sum(data2, axis=0))
print("Row-wise Sum:", np.sum(data2, axis=1))


# 14. Practical Data Analysis Example

marks = np.array([
    [80, 75, 90],
    [65, 70, 60],
    [90, 85, 95],
    [55, 60, 58],
    [75, 80, 78]
])

print("\nPractical Example:")
print("Marks:")
print(marks)

print("Overall Average:", np.mean(marks))
print("Highest Mark:", np.max(marks))
print("Lowest Mark:", np.min(marks))
print("Total Marks:", np.sum(marks))

student_average = np.mean(marks, axis=1)

print("Student Averages:", student_average)
print("Students with average >= 75:")
print(student_average[student_average >= 75])

1D Array:
[10 20 30 40 50]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Dimensions of arr1: 1
Dimensions of arr2: 2
Dimensions of arr3: 3
Shape of arr2: (2, 3)
Data type of arr1: int64

Indexing:
First element: 10
Third element: 30
Last element: 50
2D element: 6

Slicing:
1D slice: [20 30 40]
2D slice:
[[2 3]
 [5 6]]

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Arange:
[ 1  2  3  4  5  6  7  8  9 10]

Linspace:
[0.   0.25 0.5  0.75 1.  ]

Mathematical Operations:
Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]

Vectorized Operations:
Square: [ 1  4  9 16 25]
Multiply by 2: [ 2  4  6  8 10]
Add 10: [11 12 13 14 15]

Boolean Masking:
Marks greater than or equal to 50:
[67 89 76 91]

Broadcasting:
Add 5: [15 25 35 45]
Multiply by 2: [20 40 60 80]
Matrix + 1